# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f0164565c90177bfb6fccdac489fd38a"
name = "Diptyque-remake-App"
application_url = "https://diptyque-shopify.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,read_customers"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = ["https://diptyque-shopify.onrender.com/auth/callback"] 
